= Spring Data Relational

The primary goal of the http://projects.spring.io/spring-data[Spring Data] project is to make it easier to build Spring-powered applications that use data access technologies. *Spring Data Relational* offers the popular Repository abstraction based on link:spring-data-jdbc[JDBC] and link:spring-data-r2dbc[R2DBC].

== This is NOT an ORM

Spring Data Relational does not try to be an ORM. It is not a competitor to JPA.
Instead it is more of a construction kit for your personal ORM that you can define the way you like or need it.

This means that it does rather little out of the box.
But it offers plenty of places where you can put your own logic, or integrate it with the technology of your choice for generating SQL statements.

== The Aggregate Root

Spring Data repositories are inspired by the repository as described in the book Domain Driven Design by Eric Evans.
One consequence of this is that you should have a repository per Aggregate Root.
Aggregate Root is another concept from the same book and describes an entity which controls the lifecycle of other entities which together are an Aggregate.
An Aggregate is a subset of your model which is consistent between method calls to your Aggregate Root.

Spring Data Relational tries its best to encourage modelling your domain along these ideas.

== Maven Coordinates

[source,xml]
----
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-jdbc</artifactId>
    <version>1.1.0.BUILD-SNAPSHOT</version>
</dependency>
----

[source,xml]
----
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-r2dbc</artifactId>
    <version>1.1.0.BUILD-SNAPSHOT</version>
</dependency>
----

== Modules

Spring Data Relational ships with multiple modules:

* Spring Data Relational: Common infrastructure abstracting general aspects of relational database access.
* link:spring-data-jdbc[Spring Data JDBC]: Repository support for JDBC-based datasources.
* link:spring-data-r2dbc[Spring Data R2DBC]: `DatabaseClient` and repository support for reactive relational database drivers.

== Features planned for the not too distant future

=== Advanced query annotation support

* projections
* SpEL expressions

=== MyBatis per method support

The current MyBatis supported is rather elaborate in that it allows to execute multiple statements for a single method call.
But sometimes less is more, and it should be possible to annotate a method with a simple annotation to identify a SQL statement in a MyBatis mapping to be executed.

== Spring Boot integration

There is https://github.com/schauder/spring-data-jdbc-boot-starter[preliminary Spring Boot integration].

Currently you will need to build it locally.

== Getting Help

Right now the best source of information is the source code in this repository.
Especially the integration tests (if you are reading this on github, type `t` and then `IntegrationTests.java`)

We are keeping an eye on the (soon to be created) https://stackoverflow.com/questions/tagged/spring-data-jdbc[spring-data-jdbc tag on stackoverflow].

If you think you found a bug, or have a feature request please https://jira.spring.io/browse/DATAJDBC/[create a ticket in our issue tracker].

== Building from Source

You don't need to build from source to use Spring Data Relational (binaries in https://repo.spring.io[repo.spring.io]), but if you want to try out the latest and greatest, Spring Data Relational can be easily built with Maven. You also need JDK 1.8.

[indent=0]
----
	$ mvn clean install
----

=== Fast running tests

Fast running tests can be executed with a simple

[source]
----
	$ mvn test
----

This will execute unit tests and integration tests using an in-memory database.

=== Running tests with a real database

In order to run the integration tests against a specific database you need to have a local Docker installation available, and then execute.

[source]
----
	$ mvn test -Dspring.profiles.active=<databasetype>
----

This will also execute the unit tests.

Currently the following _databasetypes_ are available:

* hsql (default, does not require a running database)
* mysql
* postgres
* mariadb

=== Run tests with all databases

[source]
----
	$ mvn test -Pall-dbs
----

This will execute the unit tests, and all the integration tests with all the databases we currently support for testing. Running the integration-tests depends on Docker.

== Contributing to Spring Data Relational

Here are some ways for you to get involved in the community:

* Get involved with the Spring community by helping out on Stackoverflow for http://stackoverflow.com/questions/tagged/spring-data-jdbc[Spring Data JDBC] and http://stackoverflow.com/questions/tagged/spring-data-r2dbc[Spring Data R2DBC] by responding to questions and joining the debate.
* Create https://jira.spring.io/browse/DATAJDBC[JIRA] tickets for bugs and new features and comment and vote on the ones that you are interested in.
* Github is for social coding: if you want to write code, we encourage contributions through pull requests from http://help.github.com/forking/[forks of this repository]. If you want to contribute code this way, please reference a JIRA ticket as well, covering the specific issue you are addressing.
* Watch for upcoming articles on Spring by http://spring.io/blog[subscribing] to spring.io.

Before we accept a non-trivial patch or pull request we will need you to https://cla.pivotal.io/sign/spring[sign the Contributor License Agreement]. Signing the contributor’s agreement does not grant anyone commit rights to the main repository, but it does mean that we can accept your contributions, and you will get an author credit if we do. If you forget to do so, you'll be reminded when you submit a pull request. Active contributors might be asked to join the core team, and given the ability to merge pull requests.

== License

link:src/main/resources/license.txt[The license und which Spring Data Relational is published can be found here].
